Repository googleapis/python-pubsub, pull requests merged in 2020-03, with the labels that each got.

#38 feat(pubsub): implement max_duration_per_lease_extension option
  google/cloud/pubsub_v1/subscriber/_protocol/leaser.py
  google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
  google/cloud/pubsub_v1/types.py
  tests/unit/pubsub_v1/subscriber/test_leaser.py
  tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
Labels: cla: yes, type: feature request

#44 fix: fix changelog links to point to issues in the old repo.
  CHANGELOG.md
Labels: cla: yes, do not merge, type: docs

#49 fix: don't assert on unordered publishes after publish error
  google/cloud/pubsub_v1/publisher/_batch/thread.py
  google/cloud/pubsub_v1/publisher/_sequencer/unordered_sequencer.py
  tests/unit/pubsub_v1/publisher/sequencer/test_unordered_sequencer.py
Labels: automerge, cla: yes

#55 chore: add psutil to synth.py
  synth.py
Labels: cla: yes

#43 fix: update generated retry timings for publish and pull rpcs via synth
  google/cloud/pubsub_v1/gapic/publisher_client.py
  google/cloud/pubsub_v1/gapic/publisher_client_config.py
  google/cloud/pubsub_v1/gapic/subscriber_client.py
  google/cloud/pubsub_v1/gapic/subscriber_client_config.py
  google/cloud/pubsub_v1/gapic/transports/publisher_grpc_transport.py
  google/cloud/pubsub_v1/gapic/transports/subscriber_grpc_transport.py
  google/cloud/pubsub_v1/proto/pubsub.proto
  google/cloud/pubsub_v1/proto/pubsub_pb2.py
  synth.metadata
Labels: cla: yes

#53 test: cover the fix for sync pull with no messages
  tests/system.py
Labels: cla: yes, testing, type: process

#51 test: put RBAC tests into their own suite
  tests/system.py
Labels: cla: yes, testing, type: process

#59 fix: use client_options.api_endpoint parameter instead of ignoring it
  google/cloud/pubsub_v1/publisher/client.py
  google/cloud/pubsub_v1/subscriber/client.py
  tests/unit/pubsub_v1/publisher/test_publisher_client.py
  tests/unit/pubsub_v1/subscriber/test_subscriber_client.py
Labels: automerge, cla: yes
