Repository googleapis/python-pubsub, pull requests merged in 2020-04, with the labels that each got.

#70 fix: fix docs warnings in Sphinx 3.0+
  CHANGELOG.md
  docs/conf.py
  docs/subscriber/api/message.rst
  docs/types.rst
Labels: cla: yes, type: docs

#76 fix: restrict api-core dependency to < 1.17.0
  setup.py
Labels: cla: yes

#66 [CHANGE ME] Re-generated to pick up changes in the API or client library generator.
  .coveragerc
  .flake8
  .github/ISSUE_TEMPLATE/bug_report.md
  CONTRIBUTING.rst
  MANIFEST.in
  google/cloud/pubsub_v1/gapic/publisher_client.py
  google/cloud/pubsub_v1/gapic/publisher_client_config.py
  google/cloud/pubsub_v1/gapic/subscriber_client.py
  google/cloud/pubsub_v1/gapic/subscriber_client_config.py
  google/cloud/pubsub_v1/gapic/transports/publisher_grpc_transport.py
  google/cloud/pubsub_v1/gapic/transports/subscriber_grpc_transport.py
  google/cloud/pubsub_v1/proto/pubsub.proto
  google/cloud/pubsub_v1/proto/pubsub_pb2.py
  noxfile.py
  setup.cfg
  synth.metadata
  synth.py
  tests/unit/gapic/v1/test_publisher_client_v1.py
  tests/unit/gapic/v1/test_subscriber_client_v1.py
Labels: cla: yes

#83 docs: fix release heading in CHANGELOG
  CHANGELOG.md
Labels: cla: yes, type: docs

#80 chore: Migrate python-pubsub synth.py from artman to bazel
  synth.py
Labels: automerge, cla: yes

#58 feat: send client id with StreamingPullRequest
  google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
  tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
Labels: automerge, cla: yes

#87 fix: remove EXPERIMENTAL notice for DLQ b/c it's GA now
  google/cloud/pubsub_v1/subscriber/message.py
Labels: cla: yes

#84 [CHANGE ME] Re-generated to pick up changes in the API or client library generator.
  docs/conf.py
  synth.metadata
Labels: cla: yes

#92 chore: remove local test_utils directory
  synth.py
  test_utils/credentials.json.enc
  test_utils/scripts/circleci/get_tagged_package.py
  test_utils/scripts/circleci/twine_upload.sh
  test_utils/scripts/get_target_packages.py
  test_utils/scripts/get_target_packages_kokoro.py
  test_utils/scripts/run_emulator.py
  test_utils/scripts/update_docs.sh
  test_utils/setup.py
  test_utils/test_utils/__init__.py
  test_utils/test_utils/imports.py
  test_utils/test_utils/retry.py
  test_utils/test_utils/system.py
  test_utils/test_utils/vpcsc_config.py
Labels: cla: yes, type: cleanup
