Repository googleapis/python-pubsub, pull requests merged in 2020-02, with the labels that each got.

#1 chore: add split repo templates
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-please.yml
  .gitignore
  .kokoro/build.sh
  .kokoro/continuous/common.cfg
  .kokoro/continuous/continuous.cfg
  .kokoro/docs/common.cfg
  .kokoro/docs/docs.cfg
  .kokoro/presubmit/common.cfg
  .kokoro/presubmit/presubmit.cfg
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  .kokoro/release/common.cfg
  .kokoro/release/release.cfg
  .kokoro/trampoline.sh
  .repo-metadata.json
  CODE_OF_CONDUCT.md
  CONTRIBUTING.rst
  MANIFEST.in
  docs/conf.py
  noxfile.py
  renovate.json
  setup.py
  synth.metadata
  synth.py
  test_utils/credentials.json.enc
  test_utils/scripts/circleci/get_tagged_package.py
  test_utils/scripts/circleci/twine_upload.sh
  test_utils/scripts/get_target_packages.py
  test_utils/scripts/get_target_packages_kokoro.py
  test_utils/scripts/run_emulator.py
  test_utils/scripts/update_docs.sh
  test_utils/setup.py
  test_utils/test_utils/__init__.py
  test_utils/test_utils/imports.py
  test_utils/test_utils/retry.py
  test_utils/test_utils/system.py
  test_utils/test_utils/vpcsc_config.py
Labels: cla: yes

#25 feat: add `StreamingPullRequest.client_id` field (via synth)
  google/__init__.py
  google/cloud/__init__.py
  google/cloud/pubsub.py
  google/cloud/pubsub_v1/gapic/publisher_client.py
  google/cloud/pubsub_v1/gapic/subscriber_client.py
  google/cloud/pubsub_v1/gapic/transports/publisher_grpc_transport.py
  google/cloud/pubsub_v1/gapic/transports/subscriber_grpc_transport.py
  google/cloud/pubsub_v1/proto/pubsub.proto
  google/cloud/pubsub_v1/proto/pubsub_pb2.py
  noxfile.py
  synth.metadata
  tests/system/gapic/v1/test_system_publisher_v1.py
  tests/unit/gapic/v1/test_publisher_client_v1.py
  tests/unit/gapic/v1/test_subscriber_client_v1.py
Labels: cla: yes, type: process

#26 feat(pubsub): ordering keys
  google/cloud/pubsub_v1/publisher/_batch/base.py
  google/cloud/pubsub_v1/publisher/_batch/thread.py
  google/cloud/pubsub_v1/publisher/_sequencer/__init__.py
  google/cloud/pubsub_v1/publisher/_sequencer/base.py
  google/cloud/pubsub_v1/publisher/_sequencer/ordered_sequencer.py
  google/cloud/pubsub_v1/publisher/_sequencer/unordered_sequencer.py
  google/cloud/pubsub_v1/publisher/client.py
  google/cloud/pubsub_v1/publisher/exceptions.py
  google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py
  google/cloud/pubsub_v1/subscriber/_protocol/leaser.py
  google/cloud/pubsub_v1/subscriber/_protocol/messages_on_hold.py
  google/cloud/pubsub_v1/subscriber/_protocol/requests.py
  google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
  google/cloud/pubsub_v1/subscriber/message.py
  google/cloud/pubsub_v1/types.py
  tests/unit/pubsub_v1/publisher/batch/test_base.py
  tests/unit/pubsub_v1/publisher/batch/test_thread.py
  tests/unit/pubsub_v1/publisher/sequencer/test_ordered_sequencer.py
  tests/unit/pubsub_v1/publisher/sequencer/test_unordered_sequencer.py
  tests/unit/pubsub_v1/publisher/test_publisher_client.py
  tests/unit/pubsub_v1/subscriber/test_dispatcher.py
  tests/unit/pubsub_v1/subscriber/test_leaser.py
  tests/unit/pubsub_v1/subscriber/test_message.py
  tests/unit/pubsub_v1/subscriber/test_messages_on_hold.py
  tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
Labels: cla: yes, do not merge

#31 nit: typo
  google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
Labels: cla: yes

#32 feat: add context manager capability to subscriber
  google/cloud/pubsub_v1/subscriber/client.py
  noxfile.py
  tests/system.py
  tests/unit/pubsub_v1/subscriber/test_subscriber_client.py
Labels: cla: yes, type: feature request

#34 test: add system tests for common RBAC operations
  tests/system.py
Labels: cla: yes, testing, type: process

#37 fix: fix typo in dispatcher.py comment
  google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py
Labels: cla: yes

#40 fix: shutdown error on streaming pull callback error
  google/cloud/pubsub_v1/subscriber/futures.py
  tests/unit/pubsub_v1/subscriber/test_futures_subscriber.py
Labels: cla: yes
