Repository googleapis/python-pubsub, pull requests merged in 2020-09, with the labels that each got.

#187 test: fix flaky sequencer unit tests
  tests/unit/pubsub_v1/publisher/test_publisher_client.py
Labels: cla: yes, testing

#189 chore: Release v2.0.0
  CHANGELOG.md
Labels: api: pubsub, autorelease: pending, cla: yes

#190 fix: pass client options to publisher and subscriber clients (#166)
  google/cloud/pubsub_v1/publisher/client.py
  google/cloud/pubsub_v1/subscriber/client.py
  tests/unit/pubsub_v1/publisher/test_publisher_client.py
  tests/unit/pubsub_v1/subscriber/test_subscriber_client.py
Labels: api: pubsub, cla: yes

#152 samples: add subscription detachment sample
  samples/snippets/README.rst
  samples/snippets/iam.py
  samples/snippets/iam_test.py
Labels: cla: yes

#193 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#170 fix: convert all RPC error types to exceptions
  google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
  tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
Labels: api: pubsub, cla: yes

#197 feat: regenerate the client lib to pick new mtls env
  .kokoro/populate-secrets.sh
  .kokoro/release/common.cfg
  .kokoro/trampoline.sh
  docs/conf.py
  google/pubsub_v1/services/publisher/async_client.py
  google/pubsub_v1/services/publisher/client.py
  google/pubsub_v1/services/publisher/transports/base.py
  google/pubsub_v1/services/publisher/transports/grpc.py
  google/pubsub_v1/services/publisher/transports/grpc_asyncio.py
  google/pubsub_v1/services/subscriber/async_client.py
  google/pubsub_v1/services/subscriber/client.py
  google/pubsub_v1/services/subscriber/transports/base.py
  google/pubsub_v1/services/subscriber/transports/grpc.py
  google/pubsub_v1/services/subscriber/transports/grpc_asyncio.py
  noxfile.py
  scripts/decrypt-secrets.sh
  setup.py
  synth.metadata
  tests/unit/gapic/pubsub_v1/test_publisher.py
  tests/unit/gapic/pubsub_v1/test_subscriber.py
Labels: api: pubsub, cla: yes

#203 docs: use new call syntax in subscriber docs
  docs/subscriber/index.rst
Labels: automerge, cla: yes

#204 chore: Release v2.1.0
  CHANGELOG.md
  setup.py
Labels: autorelease: pending, cla: yes

#207 chore: clean up region tags
  samples/snippets/publisher.py
  samples/snippets/quickstart/pub.py
  samples/snippets/quickstart/sub.py
Labels: api: pubsub, cla: yes

#210 docs: fix get topic_path in subscriber sample
  docs/subscriber/index.rst
Labels: api: pubsub, automerge, cla: yes, samples
