Repository googleapis/python-pubsub, pull requests merged in 2020-06, with the labels that each got.

#96 feat: add flow control for message publishing
  google/cloud/pubsub_v1/publisher/client.py
  google/cloud/pubsub_v1/publisher/exceptions.py
  google/cloud/pubsub_v1/publisher/flow_controller.py
  google/cloud/pubsub_v1/types.py
  tests/unit/pubsub_v1/publisher/test_flow_controller.py
  tests/unit/pubsub_v1/publisher/test_publisher_client.py
Labels: cla: yes, type: feature request

#113 docs: fix update subscription/snapshot/topic samples
  google/cloud/pubsub_v1/gapic/publisher_client.py
  google/cloud/pubsub_v1/gapic/subscriber_client.py
  synth.py
Labels: cla: yes, type: docs

#114 chore: re-generated to pick up changes in the API or client library generator
  .flake8
  .gitignore
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  .kokoro/samples/lint/common.cfg
  .kokoro/samples/lint/continuous.cfg
  .kokoro/samples/lint/periodic.cfg
  .kokoro/samples/lint/presubmit.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.6/continuous.cfg
  .kokoro/samples/python3.6/periodic.cfg
  .kokoro/samples/python3.6/presubmit.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.7/continuous.cfg
  .kokoro/samples/python3.7/periodic.cfg
  .kokoro/samples/python3.7/presubmit.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/samples/python3.8/continuous.cfg
  .kokoro/samples/python3.8/periodic.cfg
  .kokoro/samples/python3.8/presubmit.cfg
  .kokoro/test-samples.sh
  MANIFEST.in
  docs/conf.py
  docs/index.rst
  docs/multiprocessing.rst
  google/cloud/pubsub_v1/gapic/publisher_client.py
  google/cloud/pubsub_v1/gapic/publisher_client_config.py
  google/cloud/pubsub_v1/gapic/subscriber_client.py
  google/cloud/pubsub_v1/gapic/transports/publisher_grpc_transport.py
  google/cloud/pubsub_v1/gapic/transports/subscriber_grpc_transport.py
  google/cloud/pubsub_v1/proto/pubsub.proto
  google/cloud/pubsub_v1/proto/pubsub_pb2.py
  google/cloud/pubsub_v1/proto/pubsub_pb2_grpc.py
  noxfile.py
  scripts/decrypt-secrets.sh
  scripts/readme-gen/readme_gen.py
  scripts/readme-gen/templates/README.tmpl.rst
  scripts/readme-gen/templates/auth.tmpl.rst
  scripts/readme-gen/templates/auth_api_key.tmpl.rst
  scripts/readme-gen/templates/install_deps.tmpl.rst
  scripts/readme-gen/templates/install_portaudio.tmpl.rst
  synth.metadata
  synth.py
  testing/.gitignore
  tests/unit/gapic/v1/test_publisher_client_v1.py
  tests/unit/gapic/v1/test_subscriber_client_v1.py
Labels: automerge, cla: yes, context: full

#108 refactor: incorporate will_accept() checks into publish()
  google/cloud/pubsub_v1/publisher/_batch/base.py
  google/cloud/pubsub_v1/publisher/_batch/thread.py
  tests/unit/pubsub_v1/publisher/batch/test_base.py
  tests/unit/pubsub_v1/publisher/batch/test_thread.py
  tests/unit/pubsub_v1/publisher/test_publisher_client.py
Labels: api: pubsub, automerge, cla: yes, type: cleanup

#103 fix: PubSub incompatibility with api-core 1.17.0+
  google/cloud/pubsub_v1/gapic/subscriber_client.py
  setup.py
  synth.py
  tests/unit/pubsub_v1/subscriber/test_subscriber_client.py
Labels: cla: yes

#123 docs: explain how to nack a sync pull message
  docs/subscriber/index.rst
Labels: cla: yes, type: docs

#127 chore(python): change autodoc_default_flags to autodoc_default_options
  docs/conf.py
  synth.metadata
Labels: cla: yes, context: full

#133 test: use 3.8 for system tests
  docs/conf.py
  google/cloud/pubsub.py
  google/cloud/pubsub_v1/gapic/publisher_client.py
  google/cloud/pubsub_v1/gapic/subscriber_client.py
  google/cloud/pubsub_v1/gapic/transports/publisher_grpc_transport.py
  google/cloud/pubsub_v1/gapic/transports/subscriber_grpc_transport.py
  google/cloud/pubsub_v1/proto/pubsub_pb2.py
  noxfile.py
  synth.metadata
  tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
Labels: cla: yes, context: partial

#134 samples: add samples from pubsub/cloud-client
  .github/CODEOWNERS
  samples/AUTHORING_GUIDE.md
  samples/CONTRIBUTING.md
  samples/snippets/README.rst
  samples/snippets/README.rst.in
  samples/snippets/iam.py
  samples/snippets/iam_test.py
  samples/snippets/noxfile.py
  samples/snippets/publisher.py
  samples/snippets/publisher_test.py
  samples/snippets/quickstart/pub.py
  samples/snippets/quickstart/pub_test.py
  samples/snippets/quickstart/sub.py
  samples/snippets/quickstart/sub_test.py
  samples/snippets/requirements-test.txt
  samples/snippets/requirements.txt
  samples/snippets/subscriber.py
  samples/snippets/subscriber_test.py
  synth.py
Labels: cla: yes, type: docs

#140 docs: added Python2 sunset notice (synth)
  docs/_templates/layout.html
  synth.metadata
Labels: cla: yes, context: partial
