Repository googleapis/python-pubsub, pull requests merged in 2021-07, with the labels that each got.

#435 fix: require grpcio >= 1.38.1 to prevent a possible crash
  setup.py
  testing/constraints-3.6.txt
Labels: api: pubsub, cla: yes

#438 docs: include docs for Pager classes
  docs/publisher/api/pagers.rst
  docs/publisher/index.rst
  docs/subscriber/api/pagers.rst
  docs/subscriber/index.rst
Labels: api: pubsub, cla: yes, documentation

#437 chore: release 2.6.1
  CHANGELOG.md
  setup.py
Labels: api: pubsub, autorelease: pending, cla: yes

#403 chore: template updates
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/fetch_gpg_keys.sh
  .kokoro/presubmit/common.cfg
  .kokoro/presubmit/presubmit.cfg
  .kokoro/samples/python3.9/common.cfg
  .kokoro/samples/python3.9/continuous.cfg
  .kokoro/samples/python3.9/periodic-head.cfg
  .kokoro/samples/python3.9/periodic.cfg
  .kokoro/samples/python3.9/presubmit.cfg
  .kokoro/test-samples-impl.sh
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  docs/conf.py
  docs/multiprocessing.rst
  google/pubsub_v1/services/publisher/async_client.py
  google/pubsub_v1/services/publisher/client.py
  google/pubsub_v1/types/__init__.py
  noxfile.py
  samples/snippets/noxfile.py
  synth.metadata
Labels: api: pubsub, automerge, cla: yes, context: none

#411 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
  synth.metadata
  synth.py
Labels: api: pubsub, cla: yes

#454 chore: add note explaining google-api-core < 3.0.0dev pin
  setup.py
Labels: api: pubsub, automerge, cla: yes

#456 feat: Add Pub/Sub topic retention fields
  google/cloud/pubsub_v1/proto/pubsub.proto
  google/pubsub_v1/services/publisher/async_client.py
  google/pubsub_v1/services/publisher/client.py
  google/pubsub_v1/types/pubsub.py
  scripts/fixup_pubsub_v1_keywords.py
  tests/unit/gapic/pubsub_v1/test_publisher.py
Labels: api: pubsub, cla: yes
