Repository googleapis/python-pubsub, pull requests merged in 2021-08, with the labels that each got.

#463 chore: require CODEOWNER review and up to date branches
  .github/sync-repo-settings.yaml
Labels: api: pubsub, automerge, cla: yes

#464 chore: add api-pubsub to samples CODEOWNERS list
  .github/CODEOWNERS
Labels: api: pubsub, cla: yes, samples

#466 process: add yoshi-python group to CODEOWNERS
  .github/CODEOWNERS
Labels: api: pubsub, cla: yes

#472 fix: remove dependency on pytz
  google/cloud/pubsub_v1/subscriber/message.py
  tests/unit/pubsub_v1/subscriber/test_message.py
Labels: api: pubsub, cla: yes, automerge

#476 samples: add type hints to all samples
  samples/snippets/iam.py
  samples/snippets/iam_test.py
  samples/snippets/noxfile_config.py
  samples/snippets/publisher.py
  samples/snippets/publisher_test.py
  samples/snippets/quickstart/pub.py
  samples/snippets/quickstart/quickstart_test.py
  samples/snippets/quickstart/sub.py
  samples/snippets/schema.py
  samples/snippets/schema_test.py
  samples/snippets/subscriber.py
  samples/snippets/subscriber_test.py
Labels: api: pubsub, cla: yes, automerge, samples
