Repository googleapis/python-pubsub, pull requests merged in 2021-02, with the labels that each got.

#284 build: migrate to flakybot
  .kokoro/test-samples.sh
  .kokoro/trampoline_v2.sh
Labels: api: pubsub, cla: yes

#254 docs: update samples in documentation
  README.rst
  docs/publisher/index.rst
  docs/subscriber/index.rst
Labels: api: pubsub, cla: yes, samples

#292 feat: add graceful streaming pull shutdown
  google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py
  google/cloud/pubsub_v1/subscriber/_protocol/heartbeater.py
  google/cloud/pubsub_v1/subscriber/_protocol/leaser.py
  google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
  google/cloud/pubsub_v1/subscriber/futures.py
  google/cloud/pubsub_v1/subscriber/scheduler.py
  tests/system.py
  tests/unit/pubsub_v1/subscriber/test_dispatcher.py
  tests/unit/pubsub_v1/subscriber/test_futures_subscriber.py
  tests/unit/pubsub_v1/subscriber/test_heartbeater.py
  tests/unit/pubsub_v1/subscriber/test_leaser.py
  tests/unit/pubsub_v1/subscriber/test_scheduler.py
  tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
Labels: api: pubsub, cla: yes

#296 chore: Release v2.4.0
  CHANGELOG.md
  setup.py
Labels: api: pubsub, autorelease: pending, cla: yes

#298 samples: use flaky in tests
  samples/snippets/quickstart/quickstart_test.py
  samples/snippets/requirements-test.txt
  samples/snippets/subscriber_test.py
Labels: api: pubsub, cla: yes, samples
