Repository googleapis/python-pubsub, pull requests merged in 2022-04, with the labels that each got.

#637 ci: fix unit test breakages
  .github/.OwlBot.lock.yaml
  noxfile.py
Labels: api: pubsub, size: m

#612 fix(deps): require google-api-core >= 1.31.5, >= 2.3.2 on v1 release
  setup.py
Labels: api: pubsub, size: xs

#639 chore: allow releases from previous major versions
  .github/release-please.yml
  owlbot.py
Labels: api: pubsub, size: s

#638 CI: fix receive_messages_with_exactly_once_delivery_enabled
  samples/snippets/subscriber_test.py
Labels: api: pubsub, size: s

#643 fix: fix eod snippets test
  samples/snippets/subscriber_test.py
Labels: api: pubsub, size: s

#648 CI: add samples python 3.9, 3.10 to required checks
  .github/sync-repo-settings.yaml
Labels: api: pubsub, samples, size: xs

#653 Samples(test): Extend timeout eod receive test
  samples/snippets/subscriber_test.py
Labels: api: pubsub, size: s

#657 docs: mark exactly once as preview feature
  google/cloud/pubsub_v1/subscriber/message.py
  samples/snippets/subscriber.py
Labels: api: pubsub, size: s

#660 Docs: fix typo in project_path in upgrade guide
  UPGRADING.md
Labels: api: pubsub, size: xs

#667 tests: separate eod creation and receive in parallel tests
  samples/snippets/subscriber_test.py
Labels: api: pubsub, samples, size: m
