Repository googleapis/python-pubsub, pull requests merged in 2022-10, with the labels that each got.

#798 Fix: Silence invalid_ack_id warnings for receipt modacks
  google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
  tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
Labels: api: pubsub, size: m

#801 fix(deps): allow protobuf 3.19.5
  setup.py
  testing/constraints-3.7.txt
Labels: api: pubsub, size: xs

#802 fix: batch at most 1,000 ack ids per request
  google/cloud/pubsub_v1/subscriber/_protocol/dispatcher.py
  tests/unit/pubsub_v1/subscriber/test_dispatcher.py
Labels: api: pubsub, size: s

#804 chore(main): release 2.13.9
  CHANGELOG.md
  setup.py
  testing/constraints-3.7.txt
Labels: api: pubsub, size: s

#805 chore: release as 2.3.10
  setup.py
Labels: api: pubsub, size: xs
