Repository googleapis/python-pubsub, pull requests merged in 2022-06, with the labels that each got.

#700 docs: fix changelog header to consistent size
  CHANGELOG.md
Labels: api: pubsub, size: xs

#699 fix(deps): require protobuf <4.0.0dev
  setup.py
  testing/constraints-3.6.txt
Labels: api: pubsub, automerge, size: xs

#704 chore: test minimum dependencies in python 3.7
  testing/constraints-3.7.txt
Labels: api: pubsub, size: s

#698 ci: add owlbot-post-processor to required checks
  .github/sync-repo-settings.yaml
Labels: api: pubsub, size: xs

#714 fix(deps): require protobuf<4.0.0 on v1 branch
  noxfile.py
  setup.py
Labels: api: pubsub, size: xs

#693 fix: change info logs to debug
  google/cloud/pubsub_v1/subscriber/_protocol/heartbeater.py
  google/cloud/pubsub_v1/subscriber/_protocol/leaser.py
  google/cloud/pubsub_v1/subscriber/_protocol/streaming_pull_manager.py
  samples/snippets/subscriber.py
  tests/unit/pubsub_v1/subscriber/test_leaser.py
  tests/unit/pubsub_v1/subscriber/test_streaming_pull_manager.py
Labels: api: pubsub, size: s
