Repository googleapis/python-pubsub, pull requests merged in 2023-04, with the labels that each got.

#893 samples: cleanup test resources
  samples/snippets/schema_test.py
  samples/snippets/subscriber_test.py
Labels: api: pubsub, samples, size: l

#880 ci: do not run 3.6 tests by default
  samples/snippets/noxfile_config.py
Labels: api: pubsub, size: s

#894 docs: Fix formatting of request arg in docstring
  google/pubsub_v1/services/publisher/async_client.py
  google/pubsub_v1/services/publisher/client.py
  google/pubsub_v1/services/schema_service/async_client.py
  google/pubsub_v1/services/schema_service/client.py
  google/pubsub_v1/services/subscriber/async_client.py
  google/pubsub_v1/services/subscriber/client.py
  google/pubsub_v1/types/pubsub.py
  google/pubsub_v1/types/schema.py
  samples/generated_samples/snippet_metadata_google.pubsub.v1.json
Labels: api: pubsub, size: m

#895 CI: Add typed_flaky to streaming_pull system tests
  noxfile.py
  owlbot.py
  tests/system.py
Labels: api: pubsub, size: m

#899 ci: use python 3.8 for pubsublite samples testing
  .kokoro/presubmit-against-pubsublite-samples.sh
Labels: api: pubsub, samples, size: s

#900 Deps: Bump grpcio version to 1.51.3
  setup.py
  testing/constraints-3.7.txt
Labels: api: pubsub, size: xs

#905 Docs: Add comment to setup.py
  setup.py
Labels: api: pubsub, automerge, size: xs
