Repository googleapis/python-pubsub, pull requests merged in 2024-11, with the labels that each got.

#1288 fix: Mark test_streaming_pull_max_messages flaky
  tests/system.py
Labels: api: pubsub, kokoro:force-run, size: xs

#1281 feat: Add support for Python 3.13
  .github/.OwlBot.lock.yaml
  .github/workflows/unittest.yml
  CONTRIBUTING.rst
  noxfile.py
  owlbot.py
  setup.py
  testing/constraints-3.13.txt
Labels: api: pubsub, size: s

#1297 test: add type flaky to unit test
  noxfile.py
  owlbot.py
  setup.py
  tests/unit/pubsub_v1/publisher/test_publisher_client.py
Labels: api: pubsub, size: s

#1298 chore: partial revert of #1297
  noxfile.py
  owlbot.py
  setup.py
Labels: api: pubsub, size: xs
